// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveXLSXsToPDFDir(arg1) {
  return window['go']['internal']['App']['SaveXLSXsToPDFDir'](arg1);
}
