// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function SaveXLSXsToPDFDir(arg1:Array<internal.FileData>):Promise<void>;
