name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: 'JobPostingPDFConverter', platform: windows/amd64, os: windows-latest},
          {name: 'JobPostingPDFConverter', platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true